# Generated by Django 5.2 on 2025-04-25 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название статьи')),
                ('content', models.TextField(verbose_name='Контент статьи')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='MainPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='main_page/images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Контент главной страницы',
                'verbose_name_plural': 'Контент главной страницы',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название раздела')),
                ('description', models.CharField(max_length=255, verbose_name='Описание раздела')),
                ('slug', models.SlugField(blank=True, max_length=30, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Период времени в десятилетиях')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Период',
                'verbose_name_plural': 'Периоды',
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles/images/', verbose_name='Изображение')),
                ('cover', models.BooleanField(default=False, verbose_name='Обложка')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.article', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Изображение статьи',
                'verbose_name_plural': 'Изображения статей',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.section', verbose_name='Раздел'),
        ),
        migrations.AddField(
            model_name='article',
            name='time_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.timeperiod', verbose_name='Период времени'),
        ),
        migrations.CreateModel(
            name='Tradition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название традиции')),
                ('content', models.TextField(verbose_name='Контент традиции')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Слаг')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Традиция',
                'verbose_name_plural': 'Традиции',
            },
        ),
        migrations.CreateModel(
            name='TraditionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles/images/', verbose_name='Изображение')),
                ('cover', models.BooleanField(default=False, verbose_name='Обложка')),
                ('tradition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.tradition', verbose_name='Традиция')),
            ],
            options={
                'verbose_name': 'Изображение традиции',
                'verbose_name_plural': 'Изображения традиций',
            },
        ),
    ]
