# Generated by Django 5.2 on 2025-04-25 05:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Контент статьи'),
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tradition',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Контент традиции'),
        ),
    ]
