# Generated by Django 5.2 on 2025-04-25 05:13

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_article_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Контент статьи'),
        ),
        migrations.AlterField(
            model_name='mainpagecontent',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tradition',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Контент традиции'),
        ),
    ]
