# Generated by Django 5.2 on 2025-04-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_timeperiod_image_alter_mainpagecontent_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeperiod',
            name='image',
            field=models.ImageField(upload_to='time_period/images/', verbose_name='Изображение'),
        ),
    ]
