# Generated by Django 5.2 on 2025-04-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_timeperiod_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeperiod',
            name='start_year',
            field=models.IntegerField(default=1950, verbose_name='Начальный год'),
        ),
    ]
