# Generated by Django 5.2 on 2025-04-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_timeperiod_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeperiod',
            name='start_year',
            field=models.IntegerField(verbose_name='Начальный год'),
        ),
    ]
