# Generated by Django 5.2 on 2025-04-25 07:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_section_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='icon',
            field=models.ImageField(upload_to='icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])], verbose_name='Иконка'),
        ),
    ]
