# Generated by Django 5.2 on 2025-05-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_tradition_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default='', max_length=200, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='tradition',
            name='description',
            field=models.TextField(default='', max_length=200, verbose_name='Краткое описание'),
        ),
    ]
