# Generated by Django 5.2 on 2025-05-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_article_description_tradition_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='tradition',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Краткое описание'),
        ),
    ]
